### ISSUE TITLE
NPCs prevent conflict in safe zones

### ISSUE THREAD

**Issue by sqrw** [sqrw/sqrw.github.io#48]
If criminals enter a safe zone NPCs will intercept (and stations shoot at them), should this be 'in alpha'?

**Comment by StarCitizenTracker** [comment]
What was said is:

> "depending on what happens or where the battles happen you know the UEE may step in so you know two organizations cannot go toe-to-toe out in the orbital space of Earth"

Which is very different from how it works at the moment.

### Not implemented

**Comment by sqrw** [comment]
Good point!
